############################ Default configuration #########################
baseURL = "https://www.yu-chong.com"
languageCode = "en-us"
# site title 
title = "Yu-chong"
# theme
theme = "northendlab-hugo"
# post pagination
paginate = "5"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "yu-chong"

[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]

########################## Plugings ######################################

# css plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"

# js plugins
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/search/fuse.min.js"
[[params.plugins.js]]
URL = "plugins/search/mark.js"
[[params.plugins.js]]
URL = "plugins/search/search.js"


########################### Navigation ###################################

# main menu

[[menu.main]]
URL = "about"
name = "about"
weight = 1

[[menu.main]]
URL = "projects"
name = "projects"
weight = 2

[[menu.main]]
URL = "blogs"
name = "blogs"
weight = 3

[[menu.main]]
URL = "tools"
name = "Recommendation"
weight = 4

[[menu.main]]
URL = "contact"
name = "contact"
weight = 5

[[menu.main]]
URL = "https://www.wuyuchong.com"
name = "中文"
weight = 6

# footer menu
[[menu.footer]]
URL = "中文"
name = "中文"
weight = 1


######################### Default Parameters ###########################
[params]
# home
home = "Home"
# logo
logo = "images/logo.svg"
# meta data
author = "Yu-chong"
description = "Yu-chong's personal website"
# google analitycs ID
googleAnalitycsID = "UA-154227155-1"
# contact form action
contactFormAction = "#" # contact form works with : https://formspree.io

# copyright
[params.footer]
copyright = "&copy; 2019 [www.yu-chong.com](https://www.yu-chong.com) All Rights Reserved"

# preloader
[params.preloader]
enable = true
preloader = "" # use png, jpg, svg or gif format

# search
[params.search]
enable = true


####################### banner #######################################
[params.banner]
bgImage = "images/banner/bg.png"


######################## call to action ###############################
[params.cta]
enable = true
image = "images/construction.svg"
title = "Under Construction"
description = "Welcome to <br> www.yu-chong.com <br> This website has just been established and still under construction"
[params.cta.button]
enable = false

[params.cta2]
enable = true
image = "images/chinese.svg"
title = "中文"
description = "www.wuyuchong.com <br> for the Chinese version"
[params.cta2.button]
enable = true
label = "中文版"
link = "https://www.wuyuchong.com"


############################## Social Site ##########################
[[params.social]]
icon = "ti-facebook" # themify icon pack https://themify.me/themify-icons
link = "https://www.facebook.com/yuchong.wu.391?ref=bookmarks"
[[params.social]]
icon = "ti-twitter-alt" # themify icon pack https://themify.me/themify-icons
link = "https://twitter.com/Ethan95457859"
[[params.social]]
icon = "ti-github" # themify icon pack https://themify.me/themify-icons
link = "https://github.com/wuyuchong"
[[params.social]]
icon = "ti-linkedin" # themify icon pack https://themify.me/themify-icons
link = "https://www.linkedin.com/in/yuchong-wu-a0a919199/"
