---
title: "WU, Yuchong"
description: "Personal Website of Yuchong Wu"
author: "Yu-chong"
categories:
date: "2019-12-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

***

<center>

[**Download CV (PDF)**](简历_吴宇翀_中央财经大学_经济统计学.pdf)

</center>

***

## EDUCATION

***

### Central University of Finance and Economics

<div align="right">Sep 2017 - Jun 2021</div>

<div align="right">Beijing, China</div>

Subject: Economic Statistics

Minor: Finance

+ Courses: 1. Mathematics (mathematical analysis, advanced algebra, etc.) 2. Statistics (probability, mathematical statistics, time series, multivariate statistics, etc.) 3. Economics (macromicro, econometrics, accounting, civil and commercial law, accounting Studies, etc.) 4. Computing (python, c, c ++, statistical calculation, data mining, etc.)
+ Big Data analysis program: using the R language to deal with large data and  writing business reports.

### University of Michigan

<div align="right">Jul 2019 - Sep 2019</div>

<div align="right">Ann Arbor, USA</div>

Summer Program in Quantitative Methods of Social Research

+ Course Grade: Regression Analysis II (A) Categorical Data Analysis (A+)

### Uppsala University

<div align="right">Sep 2019 - Jan 2020</div>

<div align="right">Uppsala, Sweden</div>

Exchange Program for one semester

## INTERNSHIP

***

### M & A FOF Investment Center（ZRC Capital） 

<div align="right">May 2019 - Sep 2019</div>

<div align="right">Beijing, China</div>

+ Data arranging, exploration and visual analysis of listed companies in Beijing.
+ Write research reports of non-listed companies and industries, such as: "Research Report of Beijing Angrui Microelectronics Technology Co., Ltd.".

### Industrial and Commercial Bank of China · Finance & Accounting Department

<div align="right">Dec 2019 - Jan 2020</div>

<div align="right">Guangdong, China</div>

+ Study the asset and liability management, customer management, risk control and other aspects of the banking industry and write business operation reports.
+ Write VBA scripts to automate workflow for the department.
+ Use SQL to extract financial and business data and use SAS to model and performing risks control for credit card.


## PROJECT

***

### SEM (Search Engine Marketing) Business Analysis

### National Innovation Project for university students

+ A Comparative Study of Personnel Placement in the Reform of Government Institutions


## ORGANISATION

***

### Official WeChat Team of Central University of Finance and Economics

<div align="right">Sep 2018 - Sep 2019</div>

<div align="right">Beijing</div>

Minister of administration

## HONORS & AWARDS

***



##  SKILLS / CERTIFICATES AND OTHER

***

### Skill

R (proficient)

python (proficient)

Latex (proficient)

word / excel/ ppt (proficient)

VBA (proficient)

SAS (basic)

SQL (basic)

C / C++ / C# (basic)  

SPSS (basic)

HTML (basic)

Java (basic)

### Activities

Violin (Level 8)  

Singing (TOP25 in Central University of Finance and Economics Singing Contest)  

Calligraphy