---
title: "Intcomedical during the epidemic in China"
description: intcomedical
author: Yuchong Wu
date: 2020-02-05
categories: ["investment", "A-share"]
tags: ["investment", "A-share"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Background

In the past few weeks, an epidemic broke out in China, and stocks with the concept of masks and medical-prevention skyrocketed. Although the medical sector has performed well overall, in fect, it is uneven between different medical stocks.

Investigating the reason, it is estimated that medical stocks in A-share is has a large range, in which stocks with the concept of medical consumables performed quite well. These companies generally have faster market response capabilities, shorter R & D cycles, and stronger sales channels.

# Standpoint of news

The information learned from several suppliers today shows that it was not only gloves (which are well known to the public), but the shortage of medical protective consumables such as disinfectant water, disposable gloves, and protective clothing has not been alleviated at all. On the contrary, because the inventory from the last lunar year has been exhausted to date, the current Spot Market is seriously insufficient. On the other hand, the factory's production capacity is insufficient due to the inability of migrant workers to arrive on-site. Even though the regulatory department gives green lights to specific product factories in this situation, most factories still fail to reach the maximum capacity due to the absence of upstream supply chains. In terms of profit-driving, since the government department has taken over the production of the factory and adopted a regulatory approach to curbing prices while providing subsidies to specific industries in the meantime. At this time, not many related industries have made effective transformations in pursuit of ultra-high profits.

From the current **Lancet Medical Highest Specification Journal** ^[https://www.thelancet.com] 
Judging from the situation learned by foreign media, the current epidemic situation has not reached its peak. Combined with the large-scale population migration after the spring holiday, the epidemic situation is expected to be further severe. In the estimation of the epidemic situation, we use three major American airlines to estimate the epidemic situation. ^[Airlines have the ability to evaluate passenger traffic and huge interest motivation]:

+ American Airline 01/30-03/28
+ Delta Airline 02/06-04/30
+ United Airline 02/06-03/28

# Standpoint of news

The price of most mask-related stocks, such as Ogilvy Medical, has been continuously climbing up to the daily limit for several days, and the risks of investing them have been too high. So we set our sights on disposable gloves which are also in great demand. After comparing with industrial competitors, we find that Intco Medical ^[300677] , whose current stock price at 2019-02-05 is about 25.5 RMB, which is not very high. Its basic financial data are as follows:

+ The dynamic P / E ratio is currently about 30, and the median for the related companies of a similar industry is about 50.
+ 85% of operating income comes from medical protection consumables. From its official website, the main product of the company is medical disposable gloves.
+ The annual net profit in the past five years has increased year by year.
+ Sufficient cash reserves: Current assets account for more than half of total assets, more than half of which are Monetary Funds. Current liabilities are just less than half of current assets.

# Conclusion

Based on this, a decision was made today (2020-02-05) to open a long position at a reasonable point in technical analysis.

***

<center>

The content of this website does not constitute any investment advice.

[** View disclaimer **](../../disclaimer)

</center>

***

