---
title: "Adjustment to the Intco-Medical and Shuanghui-Development"
description: Adjustment to the Intco-Medical and Shuanghui-Development
author: Yuchong Wu
date: 2020-02-11
categories: ["investment", "A-share"]
tags: ["investment", "A-share"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Intco-Medical

Although the official data of confirmed cases nationwide is still climbing, and there is no sign of improvement in other news channels. However, the price of stocks in the medical and health sector has experienced a sharper decline after the previous trading day, and Inco Medical has fallen accordingly. After all, equity trading is based on the present but future-oriented, and the current valuation of medical and health stocks is already relatively high. It is not surprising that stock prices have fallen in the face of medical resource shortages.

In the short term when affected by the outbreak, we have no way of knowing whether the peak of the medical sector has passed. Although we are optimistic toward Intco-Medical in the long term, it may still be to comply with the capital market and invest when its valuation is low.

Based on this,  we decided to sell ** Intco-Medical ** at a reasonable price based on technical analysis today (2020-02-10).

This long-position trade has an average buying price of 25.75 CNY and an average selling price of 26.08 CNY. The yield is 1.28%.

# Shuanghui-Development

we are still optimistic about it in the long run and phased adjustments are made in the short run.

Based on this, we make a decision to sell ** Inco Medical ** at a reasonable price of 33.22 (11:18) based on technical analysis today (2020-02-10).

This long-position trade has an average buying price of 30.494 CNY and an average selling price of 33.220 CNY. The yield is 1.28%. ^[This price and yield exclude transaction fees and stamp duty. The handling fee is 0.025% (two-way), and the stamp duty is 0.1% (one-way). ] 

Update: Today (2020-02-10), a decision was made to open a long position again at a reasonable point based on technical analysis at 33.21 CNY (11:18).

***

<center>

The content of this website does not constitute any investment advice.

[**View disclaimer**](../../disclaimer)

</center>

***

